### PR TITLE
v3.0

### PR DESCRIPTION
**Pull request by Allerter**
- Sphinx displayed `types` attributes using the information in docstrings but they looked a bit messy. So I removed them and manually put them in a table in docs
- added checking for song_info['instrumental'] when available to avoid fetching lyrics for instrumental songs.
- renamed `album.songs` to `album.tracks`
- added the `Track` type (Note: On Genius a track just has the `number` and `song` attributes, but since `Track` inherits `BaseEntity` it will have a redundant `id` attribute and `Track.id == Track.song.id`.)
- refactored OAuth2 to only support code flow in get_user_token since the token flow already has the token in the redirected url.
- added release notes to docs (not completed yet)

### CODE REVIEW

**Comment by Allerter** [comment]
- [ ] Ready to be merged

**Comment by johnwmillr** [comment]
Hi @Allerter, I'm getting an `AttributeError: 'Tee' object has no attribute 'encoding'` error on the `test_saving_json_file` and `test_saving_txt_file`. Is this related to the VCR package? Are you getting the same error on your end?

**Comment by johnwmillr** [comment]
The PR is ready to go. All tests are passing locally for me. Thank you for your hard work on this, @Allerter.

Should we update the [package version](https://github.com/johnwmillr/LyricsGenius/blob/96bb0c616a2a777b2f37125a095c1ca3784831f8/lyricsgenius/__init__.py#L17) to 3.0.0?

**Comment by Allerter** [comment]
The tests passed on Travis CI too. I think we're ready to go.

**Comment by Allerter** [comment]
I forgot to update the release notes in the docs and on GitHub's Releases page. Please merge this PR after I commit the release notes.

**Review by johnwmillr — APPROVED** [review]
Thanks again for the excellent PR, @Allerter. I will merge it once you've finished the release notes.

**Comment by Allerter** [comment]
Happy to contribute, @johnwmillr.
I added the release notes but put question marks instead of the release day (`2021-02-??`). Please replace that when you release the new version.

**Review by johnwmillr — APPROVED** [review]

**Comment by johnwmillr** [comment]
3.0.0 is [live on PyPi](https://pypi.org/project/lyricsgenius/3.0.0/)!

**Pull request merged**
