### PR TITLE
Refactor artist to make use of Song.save_lyrics()

### PR DESCRIPTION
**Pull request by VitoMinheere**
Refactor artist to make use of Song.save_lyrics() for all the songs in the artist object

Created to_dict function on Song to create the object for the json extension option. 

Set absolute imports

Fixed some typos

Changed format_ to extension as not to confuse with Python format

### CODE REVIEW

**Comment by VitoMinheere** [comment]
Updated the tests so that they will all complete. 

Because each song for the artist is saved separately the filename parameter won't work, the files will all get the same name. Now each song is save in a different file. A check could be added that if filename is set, all the lyrics will be written to 1 file

**Comment by johnwmillr** [comment]
This is great work, Vito. Thank you! I have a busy few days, but I'll try to get to the PR soon.

**Comment by VitoMinheere** [comment]
Different extensions would also require adding more options to the main.py. This refactor will be a bit bigger than expected. 

I am not sure if using the song.save_lyrics would be the best way to proceed. That function will now write directly to a file. 
Perhaps 2 write_lyrics functions are necessary but the amount of duplicate code will need to be minimized.

**Comment by johnwmillr** [comment]
I realize my PR review was a bit disjointed. If you don't mind tackling the updates to the unit tests I requested, I'd be happy to merge the PR as is. Then, I (or both of us) can get started on some of the necessary modifications for my other requests.

Make sense?

**Comment by VitoMinheere** [comment]
I updated the tests to remove the multiple files

**Comment by johnwmillr** [comment]
Good work! I'm happy with the changes you made and will merge the PR. I'll start work on a new branch implementing the lyrics saving options you described above. You're more than welcome to contribute.

**Comment by johnwmillr** [comment]
Resolves #80

**Pull request merged**
