### PR TITLE
Added get_referents() and get_song_annotations() functions

### LINKED ISSUE #100: Get referents
**Handle song's referents in order to get annotations id**
Referents are the sections of a piece of content to which annotations are attached. Each referent is associated with a web page or a song and may have one or more annotations. Referents can be searched by the document they are attached to or by the user that created them : [referents](https://docs.genius.com/#referents-h2)

- To get referents : referents?song_id=id

- From the returned JSON we have array of referents in ["response"]["referents"]

- From a referent we have annotations id in ["annotations"][annotation_indice]["id"]

We can build a list of annotations id and use it for [Genius.get_annotation(id_)](https://github.com/johnwmillr/LyricsGenius/blob/49f7d573efad5d1a633a73480b2a99d50c237b60/lyricsgenius/api.py#L104)

I hope this makes sense, I can help but I'm not familiar with GitHub collaboration atm.

### PR DESCRIPTION
**Pull request by ludehon**
get_song_annotations() can be used for getting all song's annotations from a song id. It returns a list of tuple : (fragment, list_of_annotations). Each fragment correspond to a highlighted part of the song, where people can write annotation.
Resolves #100

### CODE REVIEW

**Comment by johnwmillr** [comment]
Thanks for this PR, @ludehon! Do you have experience writing unit tests? Any chance you could add a couple that test your new functions?

**Comment by ludehon** [comment]
I never did, only checked some example and your [test_genius](https://github.com/johnwmillr/LyricsGenius/blob/master/tests/test_genius.py). 
It does't seem complicated, but I don't see what to assert since the data is coming from the API. Should I assert types, length, stuff like that ?

**Comment by johnwmillr** [comment]
Yeah, most of the tests I've written search for a specific song (or annotation in your case) whose results you know, and assert that the returned data matches up. I don't have the bandwidth at the moment to add the tests myself but can try within the next week or so.

**Comment by johnwmillr** [comment]
I noticed your API key is included in the commit history for this PR. Do you mind creating a new PR that only contains the final changes you made to the `api.py` file? That will make for a cleaner contribution in the end.

**Comment by ludehon** [comment]
Yeah I noticed that but I hesitated to point it out... I will do it asap, and will look for tests this week I think.

**Pull request closed without merging**
