### PR TITLE
Added get_referents() and get_song_annotations() functions

### LINKED ISSUE #100: Get referents
**Handle song's referents in order to get annotations id**
Referents are the sections of a piece of content to which annotations are attached. Each referent is associated with a web page or a song and may have one or more annotations. Referents can be searched by the document they are attached to or by the user that created them : [referents](https://docs.genius.com/#referents-h2)

- To get referents : referents?song_id=id

- From the returned JSON we have array of referents in ["response"]["referents"]

- From a referent we have annotations id in ["annotations"][annotation_indice]["id"]

We can build a list of annotations id and use it for [Genius.get_annotation(id_)](https://github.com/johnwmillr/LyricsGenius/blob/49f7d573efad5d1a633a73480b2a99d50c237b60/lyricsgenius/api.py#L104)

I hope this makes sense, I can help but I'm not familiar with GitHub collaboration atm.

### PR DESCRIPTION
**Pull request by ludehon**
get_song_annotations() can be used for getting all song's annotations from a song id. It returns a list of tuple : (fragment, list_of_annotations). Each fragment correspond to a highlighted part of the song, where people can write annotations.
Resolve #100

### CODE REVIEW

**Comment by ludehon** [comment]
By the way, @johnwmillr, is it possible to permanently remove #101 ?

**Comment by johnwmillr** [comment]
Thanks for the new PR. I don't think I'm able to delete PRs, but this [StackOverflow link](https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github) says you can contact [GitHub support](mailto:support@github.com) and they'll delete the PR if it contains sensitive information.

**Comment by ludehon** [comment]
Hi  again @johnwmillr, I was wondering how I could design some tests functions. The problem is the content I get from the Genius API is not fixed and therefore tests can fail in the future. I was suggested by someone I could use a locally stored result from the API, and tests my functions with that, but it imply storing data files for tests purpose.
What do you think ?

**Comment by johnwmillr** [comment]
Thanks for keeping to work on this, @ludehon! Could you post some examples here of the queries you're sending to your `get_referents` and `get_song_annotations` functions?

Does the content from Genius change because users upload new annotations? If a list is returned for a particular song, would the first (or last?) element of the list always be the same?

**Comment by jessestuart** [comment]
Hey all! Been interested recently in automating the construction of a corpus based on Genius data, came across this lovely project. This PR caught my eye, so I thought I'd chime in:

@johnwmillr:
1) I wouldn't hold my breath on getting a PR permanently deleted; GH's collaboration primitives are designed to be immutable, and [with good reason](https://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm).  However, you can easily check the PR back out (looks like the branch was deleted, but if you recreate it should stick track), perform an interactive rebase to drop any commits with sensitive data, then force push the branch, leaving no record of the mistaken commits on the Github PR page. Here's roughly how I'd go about it:

```console
$ git clone johnwmillr/LyricsGenius && cd LyricsGenius
# Fetch a reference to the original branch, so we can wipe its history.
$ git fetch origin refs/pull/101/head:annotations
#                            ^ PR#    ^ Your original fork's branch name
$ git rebase -i HEAD~8
#               ^ This is simply saying that we're going to rewrite history
#               going back 8 commits, in this case. Adjust as you see fit...
#               doesn't much matter since you're wiping history anyway, so long
#               as you get everything.
```

Drop any/all commits you don't want public, then `git push -f <your-remote>` should do the trick. Let me know if you'd like clarification on any of those steps.

2) There are plenty of great tools for doing exactly what you're looking for — the problem of "not-fixed test data" is a tale as old as QA engineering :P Many people's approach to simplify this is by taking the variability of the API out of the equation — e.g., by making an initial request during testing, automatically recording the request params + response, serializing that to disk, and replaying it back on subsequent test runs. That way you can focus on whether there's a regression in your *logic* when a test fails, rather than wondering about API flakiness, etc.  I've used tools like this in a variety of languages, but not Python, although https://github.com/kevin1024/vcrpy seems to be in line with what you're looking for.

**Comment by johnwmillr** [comment]
Wow, thank you for this, @jessestuart! These comments are a huge help. I'll try to get around to integrating all of this in the next few days.

**Comment by ludehon** [comment]
@johnwmillr Sorry for the late response, here is an example of the functions :

To access song's annotations (you need the song's id) :
```
song_id = 873

g = Genius("access_token")
annotations = g.get_song_annotations(song_id)

for a in annotations:
    print(a)
```

> Does the content from Genius change because users upload new annotations?

In my opinion, since almost anyone can add annotations, any result content or length can change. And annotations can be added to any fragment of the song, but it seems they may be appended to the end of the annotations list (it is not specified by Genius).

> If there is date metadata associated with annotations, can you sort by date, ensuring that the earliest post will always be first?

I searched in the returned JSON and only found two timestamps at referent["annotatable"]["client_timestamps"]
For example :
```
referents = g.get_referents(song_id)
print(referents["referents"][0]["annotatable"]["client_timestamps"])
```
However I don't know how to use these timestamps : {'updated_by_human_at': 1556991479, 'lyrics_updated_at': 1560888793} (didn't find infos on it).

Afaik there is no way to sort by date.


Perhaps we can test the first annotation of a famous song that will not likely to be changed.

**Comment by johnwmillr** [comment]
@ludehon, thanks for putting this together! I've cleaned up the methods and added tests with what you've put together. I'm relying on consistent responses from the API for the tests and am happy with that method until it breaks... 🙄  Going forward, I'd love to have tests using the `vcrpy` module like @jessestuart suggested.

**Comment by ludehon** [comment]
@johnwmillr I was kinda busy lately, I will have more free time now. I will look into `vcrpy` for consistent tests !

**Comment by johnwmillr** [comment]
Yes, your code will be more consistent if you create pull in changes from the `master` branch. You shouldn't have to create a new fork to do this, but that may be the easiest route. It'd be great if you could work on the `vcrpy` tests!

**Comment by ludehon** [comment]
Hi again @johnwmillr, I looked at `vrcpy` and tested the vcr decorator for consistent tests. It seems to work well since it stores cache data in files (JSON response).

I pushed changes on [my fork](https://github.com/ludehon/LyricsGenius/commit/3a5d85246868a1f39bbdbd268511df18fb461244), tell me if it's ok.

**Comment by johnwmillr** [comment]
Yes, this looks like a good step forward. Are the VCR cache files stored locally? They're copies of the network traffic?

**Comment by ludehon** [comment]
By using `@vcr.use_cassette()` without filename in parameter, the file is stored locally next to the script that calls the decorated function. 
For example, when testing `@vcr.use_cassette() def test_get_song_annotations(self): `
the file _/tests/test_get_song_annotations_ is produced, and contains the HTTP GET data received (see [attached file](https://github.com/johnwmillr/LyricsGenius/files/3586395/test_get_song_annotations.txt), I had to change extension because of github).

**Comment by johnwmillr** [comment]
@ludehon, you can go ahead and open a PR that adds `vcrpy` functionality.

**Pull request merged**
