### PR TITLE
Unicode support

### PR DESCRIPTION
**Pull request by JakeStanger**
Encode lyrics as `utf8`, write lyrics in binary format.

### CODE REVIEW

**Comment by johnwmillr** [comment]
Thanks for opening this PR, Jake. Are these changes in response to errors you were getting?

**Comment by JakeStanger** [comment]
Hi John, yes it is in response to an error. I really should have specified that. It's the `UnicodeEncodeError: ascii can't encode character...` error thrown when saving lyrics containing non-ascii characters. I will quickly make that suggested change.

**Comment by JakeStanger** [comment]
All appears to be working as intended for me. Only downside is having to decode the lyrics to use them. Should the `lyrics` property return the decoded form?

**Comment by johnwmillr** [comment]
Do you mind giving a few examples of searches that lead to the `UnicodeEncodeError`?

**Comment by JakeStanger** [comment]
I know there's been a few cases but first example that comes to mind is `Thirty Years` by `U.K` from their self-titled album. It contains a hyphen character which is U+2013 as opposed to the ASCII dash.

**Comment by johnwmillr** [comment]
Hmm, I did a song search for the U.K. song
```python
song = api.search_song('Thirty Years', 'U.K.')
song.save_lyrics()
```
and that ran without issue.

It's not that I don't want to fix this issue - I do appreciate your efforts! - I just want a better sense of the types of errors we're getting before going ahead with the merge.

**Comment by JakeStanger** [comment]
I'll try and find some more examples today. Also I have encountered the problem with both Python 3.6 and 3.7 so it's not that.

**Comment by JakeStanger** [comment]
Error I'm getting for UK - Thirty Years: `UnicodeEncodeError: 'ascii' codec can't encode character '\\u2013' in position 704: ordinal not in range(128)`

Found another one with Radioland by Kraftwerk: `UnicodeEncodeError: 'ascii' codec can't encode character '\\xe4' in position 192: ordinal not in range(128)`

And Nachrichten by Kraftwerk: `UnicodeEncodeError: 'ascii' codec can't encode character '\\xfc' in position 52: ordinal not in range(128)`

And Sun In The Night by Brand X: `UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-6: ordinal not in range(128)`

**Comment by johnwmillr** [comment]
Thanks for these examples, Jake. I was actually able to download each of the songs you listed without error. Do you run into the error during the search, or is it after you've downloaded the song and are trying to save the lyrics?

I'd like to pin down what's causing the error for some users but not all. Issue #43 is another example of a bug for some users that I haven't been able to recreate on my own.

**Comment by JakeStanger** [comment]
Each of these are thrown at `lyrics_file.write(lyrics_to_write)` (`save_lyrics`, line 145). 

Further: I'm also running it on Linux, haven't tried it on another OS, although I cannot imagine that would make a difference.

**Comment by johnwmillr** [comment]
Okay, I'll have to keep digging around. I'm not getting any errors. I will add one of your examples as a test on Travis-CI to see if there is an error in that environment.

**Comment by johnwmillr** [comment]
Do you have any suggestions for how we can test this on other platforms? I'd like to pin down what's causing these bugs in some environments but not all.

**Comment by JakeStanger** [comment]
I can test on various Linux distros and Windows. Different virtualenv setups would seem like a sensible way to go although I'm not really sure what to suggest or where to start. Perhaps others with the issue could do a pip freeze and we can look for common packages?

**Comment by johnwmillr** [comment]
I'm at a bit of a loss as to what might be causing the error. `virtualenv` lets you use different Python versions, but it's not going to let us test out different OS's.

I'm *guessing* it's something to do with how the different platforms each deal with Unicode decoding. My hunch is it will take some reading up on Unicode differences between platforms.

**Comment by JakeStanger** [comment]
I've just done some quick reading myself. There is definitely [evidence](https://stackoverflow.com/questions/35502328/unicodeencodeerror-on-linux-but-not-on-windows) this is a Linux-only problem and does not occur on Windows. It looks like the technical reason is that while Linux uses the system default locale and that only, the Windows implementation somewhere overrides encoding missing characters and tries to fill in the blanks. More on that [here](https://bugs.python.org/issue19846).

**Comment by johnwmillr** [comment]
Hmm, I'm using a Mac. And the [Travis-CI tests](https://travis-ci.org/johnwmillr/LyricsGenius/builds/414577858) are on Ubuntu.

**Comment by JakeStanger** [comment]
Are you able to get the output of `locale` (or mac equiv)? 

For reference on my Arch machine:

```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=en_GB.UTF-8
```

And my Debian server:
```
LANG=en_GB.UTF-8
LANGUAGE=en_GB:en
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Comment by johnwmillr** [comment]
From my Mac running macOS 10.13.6:

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by JakeStanger** [comment]
I can test it right now, but I can set up a VM when I get the chance and I'll try fiddling with the language settings and seeing if it makes any difference.

**Comment by JakeStanger** [comment]
Just tried a fresh Arch install in Vagrant ,with a fresh Python install, this package cloned from the repo, and nothing else. Lyrics appear to be saving without a problem for both US and GB locales.

**Comment by johnwmillr** [comment]
Argh! I appreciate you following up on this. I'm at a loss as well, I'm not sure what next steps to take.

**Comment by JakeStanger** [comment]
Ok how about as opposed to enforcing binary encoding I make it a false-by-default parameter for the save_lyrics function (and possibly pass it through accordingly)? More option sounds better all round.

Hopefully we'll find out the reason why eventually.

**Comment by johnwmillr** [comment]
That would be an okay approach for now.

**Comment by JakeStanger** [comment]
Not sure whether this approach is satisfactory but it's certainly the easiest way.

**Comment by johnwmillr** [comment]
Okay, I like the optional binary encoding. Thanks for making those changes. I added the same binary encoding option to the `Artist` class.

I'll merge the PR now. Eventually I'd love to figure out what's really going on here!

**Comment by JakeStanger** [comment]
Cheers! Thanks for accepting them, and hopefully we'll get to the bottom of this eventually.

**Comment by johnwmillr** [comment]
Sure thing! Please feel free to contribute again in the future. Hopefully the next issue is a little less nebulous...

**Pull request merged**
