### PR TITLE
fix ads and other unwanted content in lyrics

### PR DESCRIPTION
**Pull request by xathon**
This PR not only contains a fix for the embed string in the end of the lyrics, but also the ticket ads and contributor numbers that have shown up in my scrapes.

### CODE REVIEW

**Review by vinchilive — APPROVED** [review]
Looks good
before:
```
2 ContributorsSubmission Lyrics[Verse 1]
Paving the way for the worst of us
To elevate themselves
Taking their pound of flesh
Moving to take the helm

[Refrain 1]
Someone to lead the way
Someone to lead the way
Down on my knees again

[Verse 2]
Bold as they come, trading their barbs
With the alacrity of a child
Beholden to none, taking apart
All who dare to oppose their will

[Verse 3]
There can be no reprieve
Now you've found your release
Why do we refuse to see
All you appear to be

[Refrain 2]
And now we are here again
Down on my knees again
You might also like[Verse 4]
Placating the beast, keeping our distance
From the drama that you create
Before the tension breaks
And a demon wakes

[Chorus 1]
Dedicate yourself to me
And be redeemed
You had best believe
It's my time to ascend
Dedicate yourself to me
And be redeemed
You had best believe
I'm more than you could ever be

Just submit

[Verse 5]
Feeling the heat as we enumerate
All that we gave away
Cutting our losses today
Before we are fooled again

[Verse 6]
Navigating the waters
Falling back to the same routine again
Escaping the tidal wave
Keeping our heads
Nothing can compare
[Chorus 2]
Dedicate yourself to me
And be redeemed
You had best believe
It's my time to ascend
Dedicate yourself to me
And be redeemed
You had best believe
You don't mean a thing to me
Maneuvering again
A beginning
Bludgeoning all who come between
What you have and what you need

[Bridge]
Spit into the eye
Of all who would deny
It's a game for you to analyse
Feigning disinterest
You were made for this
So take the hit
And never show fear again

[Chorus 3]
Swallowing hurricanes
In your violence
Any who dare remain
Will cower in your wake
Paving the road to hell
You and I have been deceived
Nothing else left to giveEmbed
```
after:
```
[Verse 1]
Paving the way for the worst of us
To elevate themselves
Taking their pound of flesh
Moving to take the helm

[Refrain 1]
Someone to lead the way
Someone to lead the way
Down on my knees again

[Verse 2]
Bold as they come, trading their barbs
With the alacrity of a child
Beholden to none, taking apart
All who dare to oppose their will

[Verse 3]
There can be no reprieve
Now you've found your release
Why do we refuse to see
All you appear to be

[Refrain 2]
And now we are here again
Down on my knees again
[Verse 4]
Placating the beast, keeping our distance
From the drama that you create
Before the tension breaks
And a demon wakes

[Chorus 1]
Dedicate yourself to me
And be redeemed
You had best believe
It's my time to ascend
Dedicate yourself to me
And be redeemed
You had best believe
I'm more than you could ever be

Just submit

[Verse 5]
Feeling the heat as we enumerate
All that we gave away
Cutting our losses today
Before we are fooled again

[Verse 6]
Navigating the waters
Falling back to the same routine again
Escaping the tidal wave
Keeping our heads
Nothing can compare
[Chorus 2]
Dedicate yourself to me
And be redeemed
You had best believe
It's my time to ascend
Dedicate yourself to me
And be redeemed
You had best believe
You don't mean a thing to me
Maneuvering again
A beginning
Bludgeoning all who come between
What you have and what you need

[Bridge]
Spit into the eye
Of all who would deny
It's a game for you to analyse
Feigning disinterest
You were made for this
So take the hit
And never show fear again

[Chorus 3]
Swallowing hurricanes
In your violence
Any who dare remain
Will cower in your wake
Paving the road to hell
You and I have been deceived
Nothing else left to give
```

**Comment by vinchilive** [comment]
But it removes the new line for `ads` block: 
Снимок экрана 2024-05-10 в 19 20 27
@xathon so maybe instead of `decompose` we can use `replaceWith('\n')` for `ads`?

**Comment by xathon** [comment]
Ah, good catch. I was using the function to remove the markers, so didn't see that. I'll be back home on Monday, I can put that in then.

**Comment by vinchilive** [comment]
Its not perfect either so I ended up using `lyrics = re.sub(r"(?<!\n)\n(\[)", r"\n\n\1", lyrics)` to add missing newlines before [blocks] :)

**Review by CitronDevo — APPROVED** [review]
Looks good, I tried it and it worked in my case.

**Comment by prono69** [comment]
Can anyone tell, is this patch still working?

**Comment by prono69** [comment]
> Its not perfect either so I ended up using `lyrics = re.sub(r"(?<!\n)\n(\[)", r"\n\n\1", lyrics)` to add missing newlines before [blocks] :)

Can you explain, where u used this . I mean can you tell me the line number

**Comment by vinchilive** [comment]
> Can you explain, where u used this . I mean can you tell me the line number
hey @prono69, I used it to format the output of the `search_song` function

```
song = genius.search_song(title, artist)
rawLyrics = song.lyrics if song != None else ""
lyrics = re.sub(r"(?<!\n)\n(\[)", r"\n\n\1", lyrics)
```

**Comment by DLu** [comment]
Fixes #265

**Comment by allerter** [comment]
I tried fetching a few songs and the lyrics were clean. This PR seems to be unnecessary now

**Comment by xathon** [comment]
Yeah, can confirm that it works, just had to specify the Github repo in the requirements.txt, since the pypi version doesn't have that yet. Awesome, thanks for your work!

**Pull request closed without merging**
