### PR TITLE
[fix] fix for extra text at last line of lyrics

### PR DESCRIPTION
**Pull request by gautamajay52**
Most of the times the last line of lyrics has `EmbedShare Url:CopyEmbed:Copy` as extra words.

### CODE REVIEW

**Comment by johnwmillr** [comment]
Hi @gautamajay52, could you provide a couple of examples of lyrics returning those extra words? Thanks!

**Comment by gautamajay52** [comment]
> Hi @gautamajay52, could you provide a couple of examples of lyrics returning those extra words? Thanks!

I am not getting in all songs. I am integrating this with Spotify to get the current playing lyrics. 

[Here is HTMl](https://nekobin.com/suhurayopu) that I used to get when that text appear for me while testing.

But on requesting again sometimes it doesn't appear. So it is random, but I have noticed it with a lot of songs.

**Comment by gautamajay52** [comment]
> Hi @gautamajay52, could you provide a couple of examples of lyrics returning those extra words? Thanks!

[Here is another HTML](https://nekobin.com/picejizija) 
I just got again while testing. 

Sir you can find the name of song in this html.

**Comment by gautamajay52** [comment]
> Hi @gautamajay52, could you provide a couple of examples of lyrics returning those extra words? Thanks!

Sir ! Are you able to reproduce the error?
Do I have to provide any other details?

**Comment by jam0ra** [comment]
@johnwmillr I seem to be having this issue as well with songs such as "Say So" and "Kiss Me More" by Doja Cat.

**Comment by gautamajay52** [comment]
> @johnwmillr I seem to be having this issue as well with songs such as "Say So" and "Kiss Me More" by Doja Cat.

Hey, Have you tried this fix ?

**Review by jam0ra — APPROVED** [review]

**Comment by jam0ra** [comment]
@gautamajay52 Yup seems to work fine so far!

**Comment by gautamajay52** [comment]
> @gautamajay52 Yup seems to work fine so far!

Actually, I was getting in almost all songs after doing multiple requests on the same song.
Thanks for your review.

**Review by imPH — APPROVED** [review]

**Comment by iiKurt** [comment]
There also appears to be extra header text prepended to the first line, too. When getting the div on line 137, [this is what is outputted](https://pastebin.com/7PCR91Wz). Line one has the extra text "Mood Lyrics" in an `h2` element.

Changing the pull request to this would fix both the original and this issue:
```
else:
    rem = div.find("div", class_=re.compile("Lyrics__Footer"))
    if rem:
        rem.replace_with("")
        
    header = div.find("h2", class_=re.compile("TextLabel"))
    if header:
        header.replace_with("")
```

**Comment by Acervans** [comment]
I managed to remove the extra header and footer with `div = html.find("div", class_=re.compile("^Lyrics__Container"))`

**Comment by Acervans** [comment]
> There also appears to be extra header text prepended to the first line, too. When getting the div on line 137, [this is what is outputted](https://pastebin.com/7PCR91Wz). Line one has the extra text "Mood Lyrics" in an `h2` element.
> 
> Changing the pull request to this would fix both the original and this issue:
> 
> ```
> else:
>     rem = div.find("div", class_=re.compile("Lyrics__Footer"))
>     if rem:
>         rem.replace_with("")
>         
>     header = div.find("h2", class_=re.compile("TextLabel"))
>     if header:
>         header.replace_with("")
> ```

It might only be me, but songs that have translations also have some extra text at the beginning. I solved it with:

```
        else:
            rem = div.find("div", class_=re.compile("Lyrics__Footer"))
            if rem:
                rem.replace_with("")

            header = div.find("h2", class_=re.compile("TextLabel"))
            if header:
                header.replace_with("")

            controls = div.find("div", class_=re.compile("LyricsControls"))
            if controls:
                controls.replace_with("")
```

**Pull request closed without merging**
